ENV: tag
API:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-api"
  ImageTag: "dev-f1b53fe"
  API_KEY: "key-dev"
UI:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-ui"
  ImageTag: "dev-b703814"
