ENV: prd
API:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-api"
  ImageTag: "v1.0.0"
  API_KEY: "key-dev"
UI:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-ui"
  ImageTag: "v1.0.0"
