
{{ $namespace := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ print $namespace "-web" }}
  name: {{ print $namespace "-web" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print $namespace "-web" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ print $namespace "-web" }}
    spec:
      containers:
      - image: {{ .Values.UI.Image }}:{{ .Values.UI.ImageTag }}
        name: {{ print $namespace "-web" }}
        resources: {}
status: {}
